apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .JOB_NAME }}
  namespace: {{ .KUBE_NAMESPACE }}
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  schedule: {{ .CRON_SCHEDULE }}
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: {{ .JOB_NAME }}
              image: quay.io/ukhomeofficedigital/cerberus-ui-service:{{.CERBERUS_SERVICE_TEST_TAG}}
              env:
                - name: JOB_NAME
                  value: {{.JOB_NAME}}
              envFrom:
                - secretRef:
                    name: {{.JOB_NAME}}
                    optional: false
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
              resources:
                requests:
                  memory: "2048Mi"
                  cpu: "1000m"
                limits:
                  memory: "4096Mi"
                  cpu: "2000m"
          restartPolicy: Never
