const taskMultipleGroupSelectors = [
  {
    fieldSetName: '5 selector matches',
    hasChildSet: true,
    contents: [],
    childSets: [
      {
        fieldSetName: '',
        hasChildSet: true,
        contents: [
          {
            fieldName: 'Group number',
            type: 'STRING',
            content: '2021-50',
            versionLastUpdated: null,
            propName: 'groupNumber',
          },
          {
            fieldName: 'Requesting officer',
            type: 'STRING',
            content: 'bffg',
            versionLastUpdated: null,
            propName: 'requestingOfficer',
          },
          {
            fieldName: 'Source reference',
            type: 'STRING',
            content: 'ffhtr',
            versionLastUpdated: null,
            propName: 'sourceReference',
          },
          {
            fieldName: 'Group reference',
            type: 'STRING',
            content: 'selector auto testing',
            versionLastUpdated: null,
            propName: 'groupReference',
          },
          {
            fieldName: 'Category',
            type: 'STRING',
            content: 'B',
            versionLastUpdated: null,
            propName: 'category',
          },
          {
            fieldName: 'Threat type',
            type: 'SUBTITLE',
            content: 'Class B&C Drugs inc. Cannabis',
            versionLastUpdated: null,
            propName: 'threatType',
          },
          {
            fieldName: 'Point of contact message',
            type: 'STRING',
            content: 'selector auto testing',
            versionLastUpdated: null,
            propName: 'pointOfContactMessage',
          },
          {
            fieldName: 'Point of contact',
            type: 'STRING',
            content: 'hrth',
            versionLastUpdated: null,
            propName: 'pointOfContact',
          },
          {
            fieldName: 'Inbound action',
            type: 'STRING',
            content: 'No action required',
            versionLastUpdated: null,
            propName: 'inboundActionCode',
          },
          {
            fieldName: 'Outbound action',
            type: 'STRING',
            content: 'No action required',
            versionLastUpdated: null,
            propName: 'outboundActionCode',
          },
          {
            fieldName: 'Warnings',
            type: 'STRING',
            content: 'rtht',
            versionLastUpdated: null,
            propName: 'warnings',
          },
          {
            fieldName: 'Warning Status',
            type: 'STRING',
            content: 'No',
            versionLastUpdated: null,
            propName: 'warningStatus',
          },
          {
            fieldName: 'Selector Warnings',
            type: 'STRING',
            content: 'No warnings',
            versionLastUpdated: null,
            propName: 'selectorWarnings',
          },
          {
            fieldName: 'Warning Details',
            type: 'STRING',
            content: null,
            versionLastUpdated: null,
            propName: 'warningDetails',
          },
          {
            fieldName: 'Notes',
            type: 'TEXT_AREA',
            content: 'notes',
            versionLastUpdated: null,
            propName: 'notes',
          },
          {
            fieldName: 'Creator',
            type: 'STRING',
            content: 'user',
            versionLastUpdated: null,
            propName: 'creator',
          },
          {
            fieldName: 'Selector ID',
            type: 'HIDDEN',
            content: 50,
            versionLastUpdated: null,
            propName: 'selectorId',
          },
        ],
        childSets: [
          {
            fieldSetName: 'Indicator matches',
            hasChildSet: false,
            contents: [
              {
                fieldName: 'Entity',
                type: 'TEXT_CELL',
                content: 'Organisation selector 1',
                versionLastUpdated: null,
                propName: 'entity',
              },
              {
                fieldName: 'Attribute',
                type: 'TEXT_CELL',
                content: 'telephone selector 1',
                versionLastUpdated: null,
                propName: 'attribute',
              },
              {
                fieldName: 'Operator',
                type: 'TEXT_CELL',
                content: 'equal selector 1',
                versionLastUpdated: null,
                propName: 'operator',
              },
              {
                fieldName: 'Value',
                type: 'BOOLEAN_CELL',
                content: '01234 selector 1',
                versionLastUpdated: null,
                propName: 'indicatorValue',
              },
              {
                fieldName: 'Entity',
                type: 'TEXT_CELL',
                content: 'Message selector 2',
                versionLastUpdated: null,
                propName: 'entity',
              },
              {
                fieldName: 'Attribute',
                type: 'TEXT_CELL',
                content: 'mode selector 2',
                versionLastUpdated: null,
                propName: 'attribute',
              },
              {
                fieldName: 'Operator',
                type: 'TEXT_CELL',
                content: 'in selector 2',
                versionLastUpdated: null,
                propName: 'operator',
              },
              {
                fieldName: 'Value',
                type: 'BOOLEAN_CELL',
                content: 'RORO Accompanied Freight,RORO Tourist selector 2',
                versionLastUpdated: null,
                propName: 'indicatorValue',
              },
            ],
            type: 'TABLE',
            propName: 'indicatorMatches',
          },
        ],
        type: 'STANDARD',
        propName: '',
      },
      {
        fieldSetName: '',
        hasChildSet: true,
        contents: [
          {
            fieldName: 'Group number',
            type: 'STRING',
            content: '2011-12',
            versionLastUpdated: null,
            propName: 'groupNumber',
          },
          {
            fieldName: 'Requesting officer',
            type: 'STRING',
            content: 'Peter Price',
            versionLastUpdated: null,
            propName: 'requestingOfficer',
          },
          {
            fieldName: 'Source reference',
            type: 'STRING',
            content: 'intel source',
            versionLastUpdated: null,
            propName: 'sourceReference',
          },
          {
            fieldName: 'Group reference',
            type: 'STRING',
            content: 'Local Reference',
            versionLastUpdated: null,
            propName: 'groupReference',
          },
          {
            fieldName: 'Category',
            type: 'STRING',
            content: 'B',
            versionLastUpdated: null,
            propName: 'category',
          },
          {
            fieldName: 'Threat type',
            type: 'SUBTITLE',
            content: 'National Security at the Border',
            versionLastUpdated: null,
            propName: 'threatType',
          },
          {
            fieldName: 'Point of contact message',
            type: 'STRING',
            content: 'Message for the POC',
            versionLastUpdated: null,
            propName: 'pointOfContactMessage',
          },
          {
            fieldName: 'Point of contact',
            type: 'STRING',
            content: 'Point Of Contact',
            versionLastUpdated: null,
            propName: 'pointOfContact',
          },
          {
            fieldName: 'Inbound action',
            type: 'STRING',
            content: 'Advise originator',
            versionLastUpdated: null,
            propName: 'inboundActionCode',
          },
          {
            fieldName: 'Outbound action',
            type: 'STRING',
            content: 'Full attention',
            versionLastUpdated: null,
            propName: 'outboundActionCode',
          },
          {
            fieldName: 'Warnings',
            type: 'STRING',
            content: 'Supplemental warnings',
            versionLastUpdated: null,
            propName: 'warnings',
          },
          {
            fieldName: 'Warning Status',
            type: 'STRING',
            content: 'Yes',
            versionLastUpdated: null,
            propName: 'warningStatus',
          },
          {
            fieldName: 'Selector Warnings',
            type: 'STRING',
            content: 'CTGN,VIOL,WEAP,O',
            versionLastUpdated: null,
            propName: 'selectorWarnings',
          },
          {
            fieldName: 'Warning Details',
            type: 'STRING',
            content: 'Warning details would be shown here',
            versionLastUpdated: null,
            propName: 'warningDetails',
          },
          {
            fieldName: 'Notes',
            type: 'TEXT_AREA',
            content: 'Supplemental notes',
            versionLastUpdated: null,
            propName: 'notes',
          },
          {
            fieldName: 'Creator',
            type: 'STRING',
            content: 'Joe Jones',
            versionLastUpdated: null,
            propName: 'creator',
          },
          {
            fieldName: 'Selector ID',
            type: 'HIDDEN',
            content: 51,
            versionLastUpdated: null,
            propName: 'selectorId',
          },
        ],
        childSets: [
          {
            fieldSetName: 'Indicator matches',
            hasChildSet: false,
            contents: [
              {
                fieldName: 'Entity',
                type: 'TEXT_CELL',
                content: 'Organisation 11',
                versionLastUpdated: null,
                propName: 'entity',
              },
              {
                fieldName: 'Attribute',
                type: 'TEXT_CELL',
                content: 'telephone 11',
                versionLastUpdated: null,
                propName: 'attribute',
              },
              {
                fieldName: 'Operator',
                type: 'TEXT_CELL',
                content: 'equal 11',
                versionLastUpdated: null,
                propName: 'operator',
              },
              {
                fieldName: 'Value',
                type: 'BOOLEAN_CELL',
                content: '01234 11',
                versionLastUpdated: null,
                propName: 'indicatorValue',
              },
              {
                fieldName: 'Entity',
                type: 'TEXT_CELL',
                content: 'Message 12',
                versionLastUpdated: null,
                propName: 'entity',
              },
              {
                fieldName: 'Attribute',
                type: 'TEXT_CELL',
                content: 'mode 12',
                versionLastUpdated: null,
                propName: 'attribute',
              },
              {
                fieldName: 'Operator',
                type: 'TEXT_CELL',
                content: 'in 12',
                versionLastUpdated: null,
                propName: 'operator',
              },
              {
                fieldName: 'Value',
                type: 'BOOLEAN_CELL',
                content: 'RORO Accompanied Freight 12',
                versionLastUpdated: null,
                propName: 'indicatorValue',
              },
            ],
            type: 'TABLE',
            propName: 'indicatorMatches',
          },
        ],
        type: 'STANDARD',
        propName: '',
      },
      {
        fieldSetName: '',
        hasChildSet: true,
        contents: [
          {
            fieldName: 'Group number',
            type: 'STRING',
            content: '2021-52',
            versionLastUpdated: null,
            propName: 'groupNumber',
          },
          {
            fieldName: 'Requesting officer',
            type: 'STRING',
            content: 'srg',
            versionLastUpdated: null,
            propName: 'requestingOfficer',
          },
          {
            fieldName: 'Source reference',
            type: 'STRING',
            content: 'grre',
            versionLastUpdated: null,
            propName: 'sourceReference',
          },
          {
            fieldName: 'Group reference',
            type: 'STRING',
            content: 'greger',
            versionLastUpdated: null,
            propName: 'groupReference',
          },
          {
            fieldName: 'Category',
            type: 'STRING',
            content: 'B',
            versionLastUpdated: null,
            propName: 'category',
          },
          {
            fieldName: 'Threat type',
            type: 'SUBTITLE',
            content: 'Class B&C Drugs inc. Cannabis',
            versionLastUpdated: null,
            propName: 'threatType',
          },
          {
            fieldName: 'Point of contact message',
            type: 'STRING',
            content: 'gregre',
            versionLastUpdated: null,
            propName: 'pointOfContactMessage',
          },
          {
            fieldName: 'Point of contact',
            type: 'STRING',
            content: 'greg',
            versionLastUpdated: null,
            propName: 'pointOfContact',
          },
          {
            fieldName: 'Inbound action',
            type: 'STRING',
            content: 'No action required',
            versionLastUpdated: null,
            propName: 'inboundActionCode',
          },
          {
            fieldName: 'Outbound action',
            type: 'STRING',
            content: 'No action required',
            versionLastUpdated: null,
            propName: 'outboundActionCode',
          },
          {
            fieldName: 'Warnings',
            type: 'STRING',
            content: 'rgeger',
            versionLastUpdated: null,
            propName: 'warnings',
          },
          {
            fieldName: 'Warning Status',
            type: 'STRING',
            content: 'currently unavailable',
            versionLastUpdated: null,
            propName: 'warningStatus',
          },
          {
            fieldName: 'Selector Warnings',
            type: 'STRING',
            content: 'Warnings currently unavailable',
            versionLastUpdated: null,
            propName: 'selectorWarnings',
          },
          {
            fieldName: 'Warning Details',
            type: 'STRING',
            content: null,
            versionLastUpdated: null,
            propName: 'warningDetails',
          },
          {
            fieldName: 'Notes',
            type: 'TEXT_AREA',
            content: 'notes',
            versionLastUpdated: null,
            propName: 'notes',
          },
          {
            fieldName: 'Creator',
            type: 'STRING',
            content: 'user',
            versionLastUpdated: null,
            propName: 'creator',
          },
          {
            fieldName: 'Selector ID',
            type: 'HIDDEN',
            content: 52,
            versionLastUpdated: null,
            propName: 'selectorId',
          },
        ],
        childSets: [
          {
            fieldSetName: 'Indicator matches',
            hasChildSet: false,
            contents: [
              {
                fieldName: 'Entity',
                type: 'TEXT_CELL',
                content: 'Organisation 31',
                versionLastUpdated: null,
                propName: 'entity',
              },
              {
                fieldName: 'Attribute',
                type: 'TEXT_CELL',
                content: 'telephone 31',
                versionLastUpdated: null,
                propName: 'attribute',
              },
              {
                fieldName: 'Operator',
                type: 'TEXT_CELL',
                content: 'equal 31',
                versionLastUpdated: null,
                propName: 'operator',
              },
              {
                fieldName: 'Value',
                type: 'BOOLEAN_CELL',
                content: '01234 31',
                versionLastUpdated: null,
                propName: 'indicatorValue',
              },
              {
                fieldName: 'Entity',
                type: 'TEXT_CELL',
                content: 'Message 32',
                versionLastUpdated: null,
                propName: 'entity',
              },
              {
                fieldName: 'Attribute',
                type: 'TEXT_CELL',
                content: 'mode 32',
                versionLastUpdated: null,
                propName: 'attribute',
              },
              {
                fieldName: 'Operator',
                type: 'TEXT_CELL',
                content: 'in 32',
                versionLastUpdated: null,
                propName: 'operator',
              },
              {
                fieldName: 'Value',
                type: 'BOOLEAN_CELL',
                content: 'RORO Accompanied Freight,RORO Tourist,RORO Unaccompanied Freight',
                versionLastUpdated: null,
                propName: 'indicatorValue',
              },
            ],
            type: 'TABLE',
            propName: 'indicatorMatches',
          },
        ],
        type: 'STANDARD',
        propName: '',
      },
      {
        fieldSetName: '',
        hasChildSet: true,
        contents: [
          {
            fieldName: 'Group number',
            type: 'STRING',
            content: '2021-22',
            versionLastUpdated: null,
            propName: 'groupNumber',
          },
          {
            fieldName: 'Requesting officer',
            type: 'STRING',
            content: 'Peter Price',
            versionLastUpdated: null,
            propName: 'requestingOfficer',
          },
          {
            fieldName: 'Source reference',
            type: 'STRING',
            content: 'intel source',
            versionLastUpdated: null,
            propName: 'sourceReference',
          },
          {
            fieldName: 'Group reference',
            type: 'STRING',
            content: 'Local Reference',
            versionLastUpdated: null,
            propName: 'groupReference',
          },
          {
            fieldName: 'Category',
            type: 'STRING',
            content: 'B',
            versionLastUpdated: null,
            propName: 'category',
          },
          {
            fieldName: 'Threat type',
            type: 'SUBTITLE',
            content: 'National Security at the Border',
            versionLastUpdated: null,
            propName: 'threatType',
          },
          {
            fieldName: 'Point of contact message',
            type: 'STRING',
            content: 'Message for the POC',
            versionLastUpdated: null,
            propName: 'pointOfContactMessage',
          },
          {
            fieldName: 'Point of contact',
            type: 'STRING',
            content: 'Point Of Contact',
            versionLastUpdated: null,
            propName: 'pointOfContact',
          },
          {
            fieldName: 'Inbound action',
            type: 'STRING',
            content: 'Advise originator',
            versionLastUpdated: null,
            propName: 'inboundActionCode',
          },
          {
            fieldName: 'Outbound action',
            type: 'STRING',
            content: 'Full attention',
            versionLastUpdated: null,
            propName: 'outboundActionCode',
          },
          {
            fieldName: 'Warnings',
            type: 'STRING',
            content: 'Supplemental warnings',
            versionLastUpdated: null,
            propName: 'warnings',
          },
          {
            fieldName: 'Warning Status',
            type: 'STRING',
            content: 'Yes',
            versionLastUpdated: null,
            propName: 'warningStatus',
          },
          {
            fieldName: 'Selector Warnings',
            type: 'STRING',
            content: 'CTGN,VIOL,WEAP',
            versionLastUpdated: null,
            propName: 'selectorWarnings',
          },
          {
            fieldName: 'Warning Details',
            type: 'STRING',
            content: null,
            versionLastUpdated: null,
            propName: 'warningDetails',
          },
          {
            fieldName: 'Notes',
            type: 'TEXT_AREA',
            content: 'Supplemental notes',
            versionLastUpdated: null,
            propName: 'notes',
          },
          {
            fieldName: 'Creator',
            type: 'STRING',
            content: 'Joe Jones',
            versionLastUpdated: null,
            propName: 'creator',
          },
          {
            fieldName: 'Selector ID',
            type: 'HIDDEN',
            content: 51,
            versionLastUpdated: null,
            propName: 'selectorId',
          },
        ],
        childSets: [
          {
            fieldSetName: 'Indicator matches',
            hasChildSet: false,
            contents: [
              {
                fieldName: 'Entity',
                type: 'TEXT_CELL',
                content: 'Organisation 21',
                versionLastUpdated: null,
                propName: 'entity',
              },
              {
                fieldName: 'Attribute',
                type: 'TEXT_CELL',
                content: 'telephone 21',
                versionLastUpdated: null,
                propName: 'attribute',
              },
              {
                fieldName: 'Operator',
                type: 'TEXT_CELL',
                content: 'equal 21',
                versionLastUpdated: null,
                propName: 'operator',
              },
              {
                fieldName: 'Value',
                type: 'BOOLEAN_CELL',
                content: '01234 21',
                versionLastUpdated: null,
                propName: 'indicatorValue',
              },
              {
                fieldName: 'Entity',
                type: 'TEXT_CELL',
                content: 'Message 22',
                versionLastUpdated: null,
                propName: 'entity',
              },
              {
                fieldName: 'Attribute',
                type: 'TEXT_CELL',
                content: 'mode 22',
                versionLastUpdated: null,
                propName: 'attribute',
              },
              {
                fieldName: 'Operator',
                type: 'TEXT_CELL',
                content: 'in 22',
                versionLastUpdated: null,
                propName: 'operator',
              },
              {
                fieldName: 'Value',
                type: 'BOOLEAN_CELL',
                content: 'RORO Accompanied 22',
                versionLastUpdated: null,
                propName: 'indicatorValue',
              },
            ],
            type: 'TABLE',
            propName: 'indicatorMatches',
          },
        ],
        type: 'STANDARD',
        propName: '',
      },
      {
        fieldSetName: '',
        hasChildSet: true,
        contents: [
          {
            fieldName: 'Group number',
            type: 'STRING',
            content: '2031-32',
            versionLastUpdated: null,
            propName: 'groupNumber',
          },
          {
            fieldName: 'Requesting officer',
            type: 'STRING',
            content: 'Peter Price',
            versionLastUpdated: null,
            propName: 'requestingOfficer',
          },
          {
            fieldName: 'Source reference',
            type: 'STRING',
            content: 'intel source',
            versionLastUpdated: null,
            propName: 'sourceReference',
          },
          {
            fieldName: 'Group reference',
            type: 'STRING',
            content: 'Global Reference',
            versionLastUpdated: null,
            propName: 'groupReference',
          },
          {
            fieldName: 'Category',
            type: 'STRING',
            content: 'B',
            versionLastUpdated: null,
            propName: 'category',
          },
          {
            fieldName: 'Threat type',
            type: 'SUBTITLE',
            content: 'National Security at the Border',
            versionLastUpdated: null,
            propName: 'threatType',
          },
          {
            fieldName: 'Point of contact message',
            type: 'STRING',
            content: 'Message for the POC',
            versionLastUpdated: null,
            propName: 'pointOfContactMessage',
          },
          {
            fieldName: 'Point of contact',
            type: 'STRING',
            content: 'Point Of Contact',
            versionLastUpdated: null,
            propName: 'pointOfContact',
          },
          {
            fieldName: 'Inbound action',
            type: 'STRING',
            content: 'Advise originator',
            versionLastUpdated: null,
            propName: 'inboundActionCode',
          },
          {
            fieldName: 'Outbound action',
            type: 'STRING',
            content: 'Full attention',
            versionLastUpdated: null,
            propName: 'outboundActionCode',
          },
          {
            fieldName: 'Warnings',
            type: 'STRING',
            content: 'Supplemental warnings',
            versionLastUpdated: null,
            propName: 'warnings',
          },
          {
            fieldName: 'Warning Status',
            type: 'STRING',
            content: 'Yes',
            versionLastUpdated: null,
            propName: 'warningStatus',
          },
          {
            fieldName: 'Selector Warnings',
            type: 'STRING',
            content: 'O',
            versionLastUpdated: null,
            propName: 'selectorWarnings',
          },
          {
            fieldName: 'Warning Details',
            type: 'STRING',
            content: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus',
            versionLastUpdated: null,
            propName: 'warningDetails',
          },
          {
            fieldName: 'Notes',
            type: 'TEXT_AREA',
            content: 'Supplemental notes',
            versionLastUpdated: null,
            propName: 'notes',
          },
          {
            fieldName: 'Creator',
            type: 'STRING',
            content: 'Joe Jones',
            versionLastUpdated: null,
            propName: 'creator',
          },
          {
            fieldName: 'Selector ID',
            type: 'HIDDEN',
            content: 51,
            versionLastUpdated: null,
            propName: 'selectorId',
          },
        ],
        childSets: [
          {
            fieldSetName: 'Indicator matches',
            hasChildSet: false,
            contents: [
              {
                fieldName: 'Entity',
                type: 'TEXT_CELL',
                content: 'Organisation 31',
                versionLastUpdated: null,
                propName: 'entity',
              },
              {
                fieldName: 'Attribute',
                type: 'TEXT_CELL',
                content: 'telephone 31',
                versionLastUpdated: null,
                propName: 'attribute',
              },
              {
                fieldName: 'Operator',
                type: 'TEXT_CELL',
                content: 'equal 31',
                versionLastUpdated: null,
                propName: 'operator',
              },
              {
                fieldName: 'Value',
                type: 'BOOLEAN_CELL',
                content: '01234 31',
                versionLastUpdated: null,
                propName: 'indicatorValue',
              },
              {
                fieldName: 'Entity',
                type: 'TEXT_CELL',
                content: 'Message 32',
                versionLastUpdated: null,
                propName: 'entity',
              },
              {
                fieldName: 'Attribute',
                type: 'TEXT_CELL',
                content: 'mode 32',
                versionLastUpdated: null,
                propName: 'attribute',
              },
              {
                fieldName: 'Operator',
                type: 'TEXT_CELL',
                content: 'in 32',
                versionLastUpdated: null,
                propName: 'operator',
              },
              {
                fieldName: 'Value',
                type: 'BOOLEAN_CELL',
                content: 'RORO Accompanied Freight 32',
                versionLastUpdated: null,
                propName: 'indicatorValue',
              },
            ],
            type: 'TABLE',
            propName: 'indicatorMatches',
          },
        ],
        type: 'STANDARD',
        propName: '',
      },
    ],
    type: 'STANDARD',
    propName: 'selectors',
  },
];

const taskSelectorsWarnings = [
  {
    fieldSetName: '5 selector matches',
    hasChildSet: true,
    contents: [],
    childSets: [
      {
        fieldSetName: '',
        hasChildSet: true,
        contents: [
          {
            fieldName: 'Group number',
            type: 'STRING',
            content: '2011-12',
            versionLastUpdated: null,
            propName: 'groupNumber',
          },
          {
            fieldName: 'Requesting officer',
            type: 'STRING',
            content: 'Peter Price',
            versionLastUpdated: null,
            propName: 'requestingOfficer',
          },
          {
            fieldName: 'Source reference',
            type: 'STRING',
            content: 'intel source',
            versionLastUpdated: null,
            propName: 'sourceReference',
          },
          {
            fieldName: 'Group reference',
            type: 'STRING',
            content: 'Local Reference',
            versionLastUpdated: null,
            propName: 'groupReference',
          },
          {
            fieldName: 'Category',
            type: 'STRING',
            content: 'B',
            versionLastUpdated: null,
            propName: 'category',
          },
          {
            fieldName: 'Threat type',
            type: 'SUBTITLE',
            content: 'National Security at the Border',
            versionLastUpdated: null,
            propName: 'threatType',
          },
          {
            fieldName: 'Point of contact message',
            type: 'STRING',
            content: 'Message for the POC',
            versionLastUpdated: null,
            propName: 'pointOfContactMessage',
          },
          {
            fieldName: 'Point of contact',
            type: 'STRING',
            content: 'Point Of Contact',
            versionLastUpdated: null,
            propName: 'pointOfContact',
          },
          {
            fieldName: 'Inbound action',
            type: 'STRING',
            content: 'Advise originator',
            versionLastUpdated: null,
            propName: 'inboundActionCode',
          },
          {
            fieldName: 'Outbound action',
            type: 'STRING',
            content: 'Full attention',
            versionLastUpdated: null,
            propName: 'outboundActionCode',
          },
          {
            fieldName: 'Warnings',
            type: 'STRING',
            content: 'Supplemental warnings',
            versionLastUpdated: null,
            propName: 'warnings',
          },
          {
            fieldName: 'Warning Status',
            type: 'STRING',
            content: 'Yes',
            versionLastUpdated: null,
            propName: 'warningStatus',
          },
          {
            fieldName: 'Selector Warnings',
            type: 'STRING',
            content: 'CTGN,VIOL,O',
            versionLastUpdated: null,
            propName: 'selectorWarnings',
          },
          {
            fieldName: 'Warning Details',
            type: 'STRING',
            content: 'Warning details would be shown here',
            versionLastUpdated: null,
            propName: 'warningDetails',
          },
          {
            fieldName: 'Notes',
            type: 'TEXT_AREA',
            content: 'Supplemental notes',
            versionLastUpdated: null,
            propName: 'notes',
          },
          {
            fieldName: 'Creator',
            type: 'STRING',
            content: 'Joe Jones',
            versionLastUpdated: null,
            propName: 'creator',
          },
          {
            fieldName: 'Selector ID',
            type: 'HIDDEN',
            content: 51,
            versionLastUpdated: null,
            propName: 'selectorId',
          },
        ],
        childSets: [
          {
            fieldSetName: 'Indicator matches',
            hasChildSet: false,
            contents: [
              {
                fieldName: 'Entity',
                type: 'TEXT_CELL',
                content: 'Organisation 11',
                versionLastUpdated: null,
                propName: 'entity',
              },
              {
                fieldName: 'Attribute',
                type: 'TEXT_CELL',
                content: 'telephone 11',
                versionLastUpdated: null,
                propName: 'attribute',
              },
              {
                fieldName: 'Operator',
                type: 'TEXT_CELL',
                content: 'equal 11',
                versionLastUpdated: null,
                propName: 'operator',
              },
              {
                fieldName: 'Value',
                type: 'BOOLEAN_CELL',
                content: '01234 11',
                versionLastUpdated: null,
                propName: 'indicatorValue',
              },
              {
                fieldName: 'Entity',
                type: 'TEXT_CELL',
                content: 'Message 12',
                versionLastUpdated: null,
                propName: 'entity',
              },
              {
                fieldName: 'Attribute',
                type: 'TEXT_CELL',
                content: 'mode 12',
                versionLastUpdated: null,
                propName: 'attribute',
              },
              {
                fieldName: 'Operator',
                type: 'TEXT_CELL',
                content: 'in 12',
                versionLastUpdated: null,
                propName: 'operator',
              },
              {
                fieldName: 'Value',
                type: 'BOOLEAN_CELL',
                content: 'RORO Accompanied Freight 12',
                versionLastUpdated: null,
                propName: 'indicatorValue',
              },
            ],
            type: 'TABLE',
            propName: 'indicatorMatches',
          },
        ],
        type: 'STANDARD',
        propName: '',
      },
    ],
    type: 'STANDARD',
    propName: 'selectors',
  },
];

const selectorMatches = [
  {
    fieldSetName: '',
    hasChildSet: true,
    contents: [
      {
        fieldName: 'Group number',
        type: 'STRING',
        content: '2021-50',
        versionLastUpdated: null,
        propName: 'groupNumber',
      },
      {
        fieldName: 'Requesting officer',
        type: 'STRING',
        content: 'bffg',
        versionLastUpdated: null,
        propName: 'requestingOfficer',
      },
      {
        fieldName: 'Source reference',
        type: 'STRING',
        content: 'ffhtr',
        versionLastUpdated: null,
        propName: 'sourceReference',
      },
      {
        fieldName: 'Group reference',
        type: 'STRING',
        content: 'selector auto testing',
        versionLastUpdated: null,
        propName: 'groupReference',
      },
      {
        fieldName: 'Category',
        type: 'STRING',
        content: 'B',
        versionLastUpdated: null,
        propName: 'category',
      },
      {
        fieldName: 'Threat type',
        type: 'SUBTITLE',
        content: 'Class B&C Drugs inc. Cannabis',
        versionLastUpdated: null,
        propName: 'threatType',
      },
      {
        fieldName: 'Point of contact message',
        type: 'STRING',
        content: 'selector auto testing',
        versionLastUpdated: null,
        propName: 'pointOfContactMessage',
      },
      {
        fieldName: 'Point of contact',
        type: 'STRING',
        content: 'hrth',
        versionLastUpdated: null,
        propName: 'pointOfContact',
      },
      {
        fieldName: 'Inbound action',
        type: 'STRING',
        content: 'No action required',
        versionLastUpdated: null,
        propName: 'inboundActionCode',
      },
      {
        fieldName: 'Outbound action',
        type: 'STRING',
        content: 'No action required',
        versionLastUpdated: null,
        propName: 'outboundActionCode',
      },
      {
        fieldName: 'Warnings',
        type: 'STRING',
        content: 'rtht',
        versionLastUpdated: null,
        propName: 'warnings',
      },
      {
        fieldName: 'Notes',
        type: 'TEXT_AREA',
        content: 'notes',
        versionLastUpdated: null,
        propName: 'notes',
      },
      {
        fieldName: 'Creator',
        type: 'STRING',
        content: 'user',
        versionLastUpdated: null,
        propName: 'creator',
      },
      {
        fieldName: 'Selector ID',
        type: 'HIDDEN',
        content: 50,
        versionLastUpdated: null,
        propName: 'selectorId',
      },
    ],
    childSets: [
      {
        fieldSetName: 'Indicator matches',
        hasChildSet: false,
        contents: [
          {
            fieldName: 'Entity',
            type: 'TEXT_CELL',
            content: 'Organisation selector 1',
            versionLastUpdated: null,
            propName: 'entity',
          },
          {
            fieldName: 'Attribute',
            type: 'TEXT_CELL',
            content: 'telephone selector 1',
            versionLastUpdated: null,
            propName: 'attribute',
          },
          {
            fieldName: 'Operator',
            type: 'TEXT_CELL',
            content: 'equal selector 1',
            versionLastUpdated: null,
            propName: 'operator',
          },
          {
            fieldName: 'Value',
            type: 'BOOLEAN_CELL',
            content: '01234 selector 1',
            versionLastUpdated: null,
            propName: 'indicatorValue',
          },
          {
            fieldName: 'Entity',
            type: 'TEXT_CELL',
            content: 'Message selector 2',
            versionLastUpdated: null,
            propName: 'entity',
          },
          {
            fieldName: 'Attribute',
            type: 'TEXT_CELL',
            content: 'mode selector 2',
            versionLastUpdated: null,
            propName: 'attribute',
          },
          {
            fieldName: 'Operator',
            type: 'TEXT_CELL',
            content: 'in selector 2',
            versionLastUpdated: null,
            propName: 'operator',
          },
          {
            fieldName: 'Value',
            type: 'BOOLEAN_CELL',
            content: 'RORO Accompanied Freight,RORO Tourist selector 2',
            versionLastUpdated: null,
            propName: 'indicatorValue',
          },
        ],
        type: 'TABLE',
        propName: 'indicatorMatches',
      },
    ],
    type: 'STANDARD',
    propName: '',
  },
  {
    fieldSetName: '',
    hasChildSet: true,
    contents: [
      {
        fieldName: 'Group number',
        type: 'STRING',
        content: '2011-12',
        versionLastUpdated: null,
        propName: 'groupNumber',
      },
      {
        fieldName: 'Requesting officer',
        type: 'STRING',
        content: 'Peter Price',
        versionLastUpdated: null,
        propName: 'requestingOfficer',
      },
      {
        fieldName: 'Source reference',
        type: 'STRING',
        content: 'intel source',
        versionLastUpdated: null,
        propName: 'sourceReference',
      },
      {
        fieldName: 'Group reference',
        type: 'STRING',
        content: 'Local Reference',
        versionLastUpdated: null,
        propName: 'groupReference',
      },
      {
        fieldName: 'Category',
        type: 'STRING',
        content: 'B',
        versionLastUpdated: null,
        propName: 'category',
      },
      {
        fieldName: 'Threat type',
        type: 'SUBTITLE',
        content: 'National Security at the Border',
        versionLastUpdated: null,
        propName: 'threatType',
      },
      {
        fieldName: 'Point of contact message',
        type: 'STRING',
        content: 'Message for the POC',
        versionLastUpdated: null,
        propName: 'pointOfContactMessage',
      },
      {
        fieldName: 'Point of contact',
        type: 'STRING',
        content: 'Point Of Contact',
        versionLastUpdated: null,
        propName: 'pointOfContact',
      },
      {
        fieldName: 'Inbound action',
        type: 'STRING',
        content: 'Advise originator',
        versionLastUpdated: null,
        propName: 'inboundActionCode',
      },
      {
        fieldName: 'Outbound action',
        type: 'STRING',
        content: 'Full attention',
        versionLastUpdated: null,
        propName: 'outboundActionCode',
      },
      {
        fieldName: 'Warnings',
        type: 'STRING',
        content: 'Supplemental warnings',
        versionLastUpdated: null,
        propName: 'warnings',
      },
      {
        fieldName: 'Notes',
        type: 'TEXT_AREA',
        content: 'Supplemental notes',
        versionLastUpdated: null,
        propName: 'notes',
      },
      {
        fieldName: 'Creator',
        type: 'STRING',
        content: 'Joe Jones',
        versionLastUpdated: null,
        propName: 'creator',
      },
      {
        fieldName: 'Selector ID',
        type: 'HIDDEN',
        content: 51,
        versionLastUpdated: null,
        propName: 'selectorId',
      },
    ],
    childSets: [
      {
        fieldSetName: 'Indicator matches',
        hasChildSet: false,
        contents: [
          {
            fieldName: 'Entity',
            type: 'TEXT_CELL',
            content: 'Organisation 11',
            versionLastUpdated: null,
            propName: 'entity',
          },
          {
            fieldName: 'Attribute',
            type: 'TEXT_CELL',
            content: 'telephone 11',
            versionLastUpdated: null,
            propName: 'attribute',
          },
          {
            fieldName: 'Operator',
            type: 'TEXT_CELL',
            content: 'equal 11',
            versionLastUpdated: null,
            propName: 'operator',
          },
          {
            fieldName: 'Value',
            type: 'BOOLEAN_CELL',
            content: '01234 11',
            versionLastUpdated: null,
            propName: 'indicatorValue',
          },
          {
            fieldName: 'Entity',
            type: 'TEXT_CELL',
            content: 'Message 12',
            versionLastUpdated: null,
            propName: 'entity',
          },
          {
            fieldName: 'Attribute',
            type: 'TEXT_CELL',
            content: 'mode 12',
            versionLastUpdated: null,
            propName: 'attribute',
          },
          {
            fieldName: 'Operator',
            type: 'TEXT_CELL',
            content: 'in 12',
            versionLastUpdated: null,
            propName: 'operator',
          },
          {
            fieldName: 'Value',
            type: 'BOOLEAN_CELL',
            content: 'RORO Accompanied Freight 12',
            versionLastUpdated: null,
            propName: 'indicatorValue',
          },
        ],
        type: 'TABLE',
        propName: 'indicatorMatches',
      },
    ],
    type: 'STANDARD',
    propName: '',
  },
  {
    fieldSetName: '',
    hasChildSet: true,
    contents: [
      {
        fieldName: 'Group number',
        type: 'STRING',
        content: '2021-52',
        versionLastUpdated: null,
        propName: 'groupNumber',
      },
      {
        fieldName: 'Requesting officer',
        type: 'STRING',
        content: 'srg',
        versionLastUpdated: null,
        propName: 'requestingOfficer',
      },
      {
        fieldName: 'Source reference',
        type: 'STRING',
        content: 'grre',
        versionLastUpdated: null,
        propName: 'sourceReference',
      },
      {
        fieldName: 'Group reference',
        type: 'STRING',
        content: 'greger',
        versionLastUpdated: null,
        propName: 'groupReference',
      },
      {
        fieldName: 'Category',
        type: 'STRING',
        content: 'B',
        versionLastUpdated: null,
        propName: 'category',
      },
      {
        fieldName: 'Threat type',
        type: 'SUBTITLE',
        content: 'Class B&C Drugs inc. Cannabis',
        versionLastUpdated: null,
        propName: 'threatType',
      },
      {
        fieldName: 'Point of contact message',
        type: 'STRING',
        content: 'gregre',
        versionLastUpdated: null,
        propName: 'pointOfContactMessage',
      },
      {
        fieldName: 'Point of contact',
        type: 'STRING',
        content: 'greg',
        versionLastUpdated: null,
        propName: 'pointOfContact',
      },
      {
        fieldName: 'Inbound action',
        type: 'STRING',
        content: 'No action required',
        versionLastUpdated: null,
        propName: 'inboundActionCode',
      },
      {
        fieldName: 'Outbound action',
        type: 'STRING',
        content: 'No action required',
        versionLastUpdated: null,
        propName: 'outboundActionCode',
      },
      {
        fieldName: 'Warnings',
        type: 'STRING',
        content: 'rgeger',
        versionLastUpdated: null,
        propName: 'warnings',
      },
      {
        fieldName: 'Notes',
        type: 'TEXT_AREA',
        content: 'notes',
        versionLastUpdated: null,
        propName: 'notes',
      },
      {
        fieldName: 'Creator',
        type: 'STRING',
        content: 'user',
        versionLastUpdated: null,
        propName: 'creator',
      },
      {
        fieldName: 'Selector ID',
        type: 'HIDDEN',
        content: 52,
        versionLastUpdated: null,
        propName: 'selectorId',
      },
    ],
    childSets: [
      {
        fieldSetName: 'Indicator matches',
        hasChildSet: false,
        contents: [
          {
            fieldName: 'Entity',
            type: 'TEXT_CELL',
            content: 'Organisation 31',
            versionLastUpdated: null,
            propName: 'entity',
          },
          {
            fieldName: 'Attribute',
            type: 'TEXT_CELL',
            content: 'telephone 31',
            versionLastUpdated: null,
            propName: 'attribute',
          },
          {
            fieldName: 'Operator',
            type: 'TEXT_CELL',
            content: 'equal 31',
            versionLastUpdated: null,
            propName: 'operator',
          },
          {
            fieldName: 'Value',
            type: 'BOOLEAN_CELL',
            content: '01234 31',
            versionLastUpdated: null,
            propName: 'indicatorValue',
          },
          {
            fieldName: 'Entity',
            type: 'TEXT_CELL',
            content: 'Message 32',
            versionLastUpdated: null,
            propName: 'entity',
          },
          {
            fieldName: 'Attribute',
            type: 'TEXT_CELL',
            content: 'mode 32',
            versionLastUpdated: null,
            propName: 'attribute',
          },
          {
            fieldName: 'Operator',
            type: 'TEXT_CELL',
            content: 'in 32',
            versionLastUpdated: null,
            propName: 'operator',
          },
          {
            fieldName: 'Value',
            type: 'BOOLEAN_CELL',
            content: 'RORO Accompanied Freight,RORO Tourist,RORO Unaccompanied Freight',
            versionLastUpdated: null,
            propName: 'indicatorValue',
          },
        ],
        type: 'TABLE',
        propName: 'indicatorMatches',
      },
    ],
    type: 'STANDARD',
    propName: '',
  },
  {
    fieldSetName: '',
    hasChildSet: true,
    contents: [
      {
        fieldName: 'Group number',
        type: 'STRING',
        content: '2021-22',
        versionLastUpdated: null,
        propName: 'groupNumber',
      },
      {
        fieldName: 'Requesting officer',
        type: 'STRING',
        content: 'Peter Price',
        versionLastUpdated: null,
        propName: 'requestingOfficer',
      },
      {
        fieldName: 'Source reference',
        type: 'STRING',
        content: 'intel source',
        versionLastUpdated: null,
        propName: 'sourceReference',
      },
      {
        fieldName: 'Group reference',
        type: 'STRING',
        content: 'Local Reference',
        versionLastUpdated: null,
        propName: 'groupReference',
      },
      {
        fieldName: 'Category',
        type: 'STRING',
        content: 'B',
        versionLastUpdated: null,
        propName: 'category',
      },
      {
        fieldName: 'Threat type',
        type: 'SUBTITLE',
        content: 'National Security at the Border',
        versionLastUpdated: null,
        propName: 'threatType',
      },
      {
        fieldName: 'Point of contact message',
        type: 'STRING',
        content: 'Message for the POC',
        versionLastUpdated: null,
        propName: 'pointOfContactMessage',
      },
      {
        fieldName: 'Point of contact',
        type: 'STRING',
        content: 'Point Of Contact',
        versionLastUpdated: null,
        propName: 'pointOfContact',
      },
      {
        fieldName: 'Inbound action',
        type: 'STRING',
        content: 'Advise originator',
        versionLastUpdated: null,
        propName: 'inboundActionCode',
      },
      {
        fieldName: 'Outbound action',
        type: 'STRING',
        content: 'Full attention',
        versionLastUpdated: null,
        propName: 'outboundActionCode',
      },
      {
        fieldName: 'Warnings',
        type: 'STRING',
        content: 'Supplemental warnings',
        versionLastUpdated: null,
        propName: 'warnings',
      },
      {
        fieldName: 'Notes',
        type: 'TEXT_AREA',
        content: 'Supplemental notes',
        versionLastUpdated: null,
        propName: 'notes',
      },
      {
        fieldName: 'Creator',
        type: 'STRING',
        content: 'Joe Jones',
        versionLastUpdated: null,
        propName: 'creator',
      },
      {
        fieldName: 'Selector ID',
        type: 'HIDDEN',
        content: 51,
        versionLastUpdated: null,
        propName: 'selectorId',
      },
    ],
    childSets: [
      {
        fieldSetName: 'Indicator matches',
        hasChildSet: false,
        contents: [
          {
            fieldName: 'Entity',
            type: 'TEXT_CELL',
            content: 'Organisation 21',
            versionLastUpdated: null,
            propName: 'entity',
          },
          {
            fieldName: 'Attribute',
            type: 'TEXT_CELL',
            content: 'telephone 21',
            versionLastUpdated: null,
            propName: 'attribute',
          },
          {
            fieldName: 'Operator',
            type: 'TEXT_CELL',
            content: 'equal 21',
            versionLastUpdated: null,
            propName: 'operator',
          },
          {
            fieldName: 'Value',
            type: 'BOOLEAN_CELL',
            content: '01234 21',
            versionLastUpdated: null,
            propName: 'indicatorValue',
          },
          {
            fieldName: 'Entity',
            type: 'TEXT_CELL',
            content: 'Message 22',
            versionLastUpdated: null,
            propName: 'entity',
          },
          {
            fieldName: 'Attribute',
            type: 'TEXT_CELL',
            content: 'mode 22',
            versionLastUpdated: null,
            propName: 'attribute',
          },
          {
            fieldName: 'Operator',
            type: 'TEXT_CELL',
            content: 'in 22',
            versionLastUpdated: null,
            propName: 'operator',
          },
          {
            fieldName: 'Value',
            type: 'BOOLEAN_CELL',
            content: 'RORO Accompanied 22',
            versionLastUpdated: null,
            propName: 'indicatorValue',
          },
        ],
        type: 'TABLE',
        propName: 'indicatorMatches',
      },
    ],
    type: 'STANDARD',
    propName: '',
  },
  {
    fieldSetName: '',
    hasChildSet: true,
    contents: [
      {
        fieldName: 'Group number',
        type: 'STRING',
        content: '2031-32',
        versionLastUpdated: null,
        propName: 'groupNumber',
      },
      {
        fieldName: 'Requesting officer',
        type: 'STRING',
        content: 'Peter Price',
        versionLastUpdated: null,
        propName: 'requestingOfficer',
      },
      {
        fieldName: 'Source reference',
        type: 'STRING',
        content: 'intel source',
        versionLastUpdated: null,
        propName: 'sourceReference',
      },
      {
        fieldName: 'Group reference',
        type: 'STRING',
        content: 'Local Reference',
        versionLastUpdated: null,
        propName: 'groupReference',
      },
      {
        fieldName: 'Category',
        type: 'STRING',
        content: 'B',
        versionLastUpdated: null,
        propName: 'category',
      },
      {
        fieldName: 'Threat type',
        type: 'SUBTITLE',
        content: 'National Security at the Border',
        versionLastUpdated: null,
        propName: 'threatType',
      },
      {
        fieldName: 'Point of contact message',
        type: 'STRING',
        content: 'Message for the POC',
        versionLastUpdated: null,
        propName: 'pointOfContactMessage',
      },
      {
        fieldName: 'Point of contact',
        type: 'STRING',
        content: 'Point Of Contact',
        versionLastUpdated: null,
        propName: 'pointOfContact',
      },
      {
        fieldName: 'Inbound action',
        type: 'STRING',
        content: 'Advise originator',
        versionLastUpdated: null,
        propName: 'inboundActionCode',
      },
      {
        fieldName: 'Outbound action',
        type: 'STRING',
        content: 'Full attention',
        versionLastUpdated: null,
        propName: 'outboundActionCode',
      },
      {
        fieldName: 'Warnings',
        type: 'STRING',
        content: 'Supplemental warnings',
        versionLastUpdated: null,
        propName: 'warnings',
      },
      {
        fieldName: 'Notes',
        type: 'TEXT_AREA',
        content: 'Supplemental notes',
        versionLastUpdated: null,
        propName: 'notes',
      },
      {
        fieldName: 'Creator',
        type: 'STRING',
        content: 'Joe Jones',
        versionLastUpdated: null,
        propName: 'creator',
      },
      {
        fieldName: 'Selector ID',
        type: 'HIDDEN',
        content: 51,
        versionLastUpdated: null,
        propName: 'selectorId',
      },
    ],
    childSets: [
      {
        fieldSetName: 'Indicator matches',
        hasChildSet: false,
        contents: [
          {
            fieldName: 'Entity',
            type: 'TEXT_CELL',
            content: 'Organisation 31',
            versionLastUpdated: null,
            propName: 'entity',
          },
          {
            fieldName: 'Attribute',
            type: 'TEXT_CELL',
            content: 'telephone 31',
            versionLastUpdated: null,
            propName: 'attribute',
          },
          {
            fieldName: 'Operator',
            type: 'TEXT_CELL',
            content: 'equal 31',
            versionLastUpdated: null,
            propName: 'operator',
          },
          {
            fieldName: 'Value',
            type: 'BOOLEAN_CELL',
            content: '01234 31',
            versionLastUpdated: null,
            propName: 'indicatorValue',
          },
          {
            fieldName: 'Entity',
            type: 'TEXT_CELL',
            content: 'Message 32',
            versionLastUpdated: null,
            propName: 'entity',
          },
          {
            fieldName: 'Attribute',
            type: 'TEXT_CELL',
            content: 'mode 32',
            versionLastUpdated: null,
            propName: 'attribute',
          },
          {
            fieldName: 'Operator',
            type: 'TEXT_CELL',
            content: 'in 32',
            versionLastUpdated: null,
            propName: 'operator',
          },
          {
            fieldName: 'Value',
            type: 'BOOLEAN_CELL',
            content: 'RORO Accompanied Freight 32',
            versionLastUpdated: null,
            propName: 'indicatorValue',
          },
        ],
        type: 'TABLE',
        propName: 'indicatorMatches',
      },
    ],
    type: 'STANDARD',
    propName: '',
  },
];

export { taskMultipleGroupSelectors, taskSelectorsWarnings, selectorMatches };
