const mockData = {
  id: 'DEV-20220831-799',
  status: 'NEW',
  assignee: null,
  relisted: false,
  latestVersionNumber: 3,
  notes: [
    {
      id: 'ac2df83e-9e4f-4638-bb2e-351a79a0e2b3',
      content: 'task updated',
      timestamp: '2022-09-01T10:32:48.831276746Z',
      userId: 'shakir.khan1@digital.homeoffice.gov.uk',
    },
    {
      id: '70510326-1811-4875-aef1-198f19264c3b',
      content: 'task updated',
      timestamp: '2022-08-31T08:48:10.259774903Z',
      userId: 'shakir.khan1@digital.homeoffice.gov.uk',
    },
    {
      id: 'fb216cd7-5a7c-428a-8f4b-b2f0aa7e26c0',
      content: 'task created',
      timestamp: '2022-08-31T08:47:48.068748598Z',
      userId: 'shakir.khan1@digital.homeoffice.gov.uk',
    },
  ],
  movement: {
    id: 'APIPNR:S=c85b5c5426a6696b24ac6ca7851f0987',
    status: 'PRE_ARRIVAL',
    mode: 'AIR_PASSENGER',
    description: 'group',
    groupSize: 2,
    booking: {
      reference: 'PONQVFT',
      type: null,
      paymentMethod: null,
      bookedAt: null,
      checkInAt: '2019-07-20T16:43:35Z',
      tickets: [
        {
          number: '8888000991',
          type: 'ONE-WAY',
          price: null,
        },
        {
          number: '8888000992',
          type: 'ONE-WAY',
          price: null,
        },
      ],
      country: null,
      payments: [],
      agent: {
        iata: '890534932',
        location: 'LHR, GB',
      },
    },
    journey: {
      id: 'BA0103',
      direction: null,
      arrival: {
        country: null,
        location: 'YYC',
        time: '2019-07-21T18:35:00Z',
      },
      departure: {
        country: null,
        location: 'LHR',
        time: '2019-07-21T16:40:00Z',
      },
      route: [
        'LHR',
        'YYC',
      ],
      itinerary: [
        {
          id: 'BA0103',
          arrival: {
            country: null,
            location: 'YYC',
            time: '2019-07-21T18:35:00Z',
          },
          departure: {
            country: null,
            location: 'LHR',
            time: '2019-07-21T16:40:00Z',
          },
          duration: 6900000,
        },
      ],
      duration: 6900000,
    },
    vessel: null,
    person: {
      entitySearchUrl: null,
      name: {
        first: 'ZUES CARLO 17',
        last: 'BATZ STOUP 18',
        full: 'ZUES CARLO 17 BATZ STOUP 18',
      },
      role: 'PASSENGER',
      dateOfBirth: '1976-12-10T00:00:00Z',
      gender: 'M',
      nationality: 'GB',
      document: {
        entitySearchUrl: null,
        type: 'PASSPORT',
        number: '119039375',
        validFrom: '2018-04-27T00:00:00Z',
        expiry: '2023-04-26T00:00:00Z',
        countryOfIssue: 'GB',
      },
      movementStats: null,
      frequentFlyerNumber: '680419104BA',
      ssrCodes: [
        'FQTV',
        'RQST',
        'FQTR',
      ],
    },
    otherPersons: [
      {
        entitySearchUrl: null,
        name: {
          first: 'Joe',
          last: 'Peterson',
          full: 'Joe Peterson',
        },
        role: 'PASSENGER',
        dateOfBirth: '1981-06-03T00:00:00Z',
        gender: 'M',
        nationality: 'GB',
        document: {
          entitySearchUrl: null,
          type: 'PASSPORT',
          number: 'ST0394612',
          validFrom: null,
          expiry: '2021-02-01T00:00:00Z',
          countryOfIssue: 'GB',
        },
        movementStats: {
          movementCount: 3,
          examinationCount: 2,
          seizureCount: 1,
        },
        frequentFlyerNumber: '123456',
        ssrCodes: null,
      },
    ],
    flight: {
      departureStatus: 'DEPARTURE_CONFIRMED',
      number: 'BA0103',
      operator: 'BA',
      seatNumber: '34A',
    },
    baggage: {
      numberOfCheckedBags: null,
      weight: null,
      tags: [],
    },
    vehicle: null,
    trailer: null,
    goods: null,
    haulier: null,
    account: null,
    booker: null,
    occupants: null,
  },
  risks: {
    targetingIndicators: {
      indicators: [],
      count: 0,
      score: 0,
    },
    matchedRules: [
      {
        id: 11470,
        name: 'PNR-Number in Party',
        type: 'Pre-arrival',
        priority: 'Tier 1',
        description: 'Test',
        version: 2,
        abuseTypes: [
          'Cash including AVTCs',
        ],
        indicatorMatches: [
          {
            entity: 'Booking',
            descriptor: 'numInParty',
            operator: 'greater_or_equal',
            value: '1',
          },
          {
            entity: 'Message',
            descriptor: 'mode',
            operator: 'in',
            value: '[Air Freight, Air Passenger, Fast Parcels, RORO Accompanied Freight, RORO Tourist, RORO Unaccompanied Freight]',
          },
        ],
      },
    ],
    matchedSelectorGroups: {
      groups: [],
      totalNumberOfSelectors: 0,
    },
    highestThreatLevel: {
      type: 'RULE',
      value: 'Tier 1',
    },
  },
  versions: [
    {
      number: 3,
      createdAt: '2022-09-01T10:32:48.831261066Z',
      movement: {
        id: 'APIPNR:S=c85b5c5426a6696b24ac6ca7851f0987',
        status: 'PRE_ARRIVAL',
        mode: 'AIR_PASSENGER',
        description: 'individual',
        groupSize: 1,
        booking: {
          reference: 'PONQVFT',
          type: null,
          paymentMethod: null,
          bookedAt: null,
          checkInAt: '2019-07-20T16:43:35Z',
          tickets: [
            {
              number: '8888000991',
              type: 'ONE-WAY',
              price: null,
            },
            {
              number: '8888000992',
              type: 'ONE-WAY',
              price: null,
            },
          ],
          country: null,
          payments: [],
          agent: {
            iata: '890534932',
            location: 'LHR, GB',
          },
        },
        journey: {
          id: 'BA0103',
          direction: null,
          arrival: {
            country: null,
            location: 'FRA',
            time: '2019-07-21T18:35:00Z',
          },
          departure: {
            country: null,
            location: 'LHR',
            time: '2019-07-21T16:40:00Z',
          },
          route: [
            'LHR',
            'FRA',
          ],
          itinerary: [
            {
              id: 'BA0103',
              arrival: {
                country: null,
                location: 'FRA',
                time: '2019-07-21T18:35:00Z',
              },
              departure: {
                country: null,
                location: 'LHR',
                time: '2019-07-21T16:40:00Z',
              },
              duration: 6900000,
            },
          ],
          duration: 6900000,
        },
        vessel: null,
        person: {
          entitySearchUrl: null,
          name: {
            first: 'ZUES CARLO 17',
            last: 'BATZ STOUP 18',
            full: 'ZUES CARLO 17 BATZ STOUP 18',
          },
          role: 'PASSENGER',
          dateOfBirth: '1976-12-10T00:00:00Z',
          gender: 'M',
          nationality: 'GB',
          document: {
            entitySearchUrl: null,
            type: 'PASSPORT',
            number: '119039377',
            validFrom: '2018-04-27T00:00:00Z',
            expiry: '2023-04-26T00:00:00Z',
            countryOfIssue: 'GB',
          },
          movementStats: null,
          frequentFlyerNumber: '680419104BA',
          ssrCodes: [
            'FQTV',
            'RQST',
            'FQTR',
          ],
        },
        otherPersons: [
          {
            entitySearchUrl: null,
            name: {
              first: 'Joe',
              last: 'Peterson',
              full: 'Joe Peterson',
            },
            role: 'PASSENGER',
            dateOfBirth: '1981-06-03T00:00:00Z',
            gender: 'M',
            nationality: 'GB',
            document: {
              entitySearchUrl: null,
              type: 'PASSPORT',
              number: 'ST0394612',
              validFrom: null,
              expiry: '2021-02-01T00:00:00Z',
              countryOfIssue: 'GB',
            },
            movementStats: {
              movementCount: 3,
              examinationCount: 2,
              seizureCount: 1,
            },
            frequentFlyerNumber: '123456',
            ssrCodes: null,
          },
        ],
        flight: {
          departureStatus: 'DEPARTURE_CONFIRMED',
          number: 'BA0103',
          operator: 'BA',
          seatNumber: '34A',
        },
        baggage: {
          numberOfCheckedBags: null,
          weight: null,
          tags: [],
        },
        vehicle: null,
        trailer: null,
        goods: null,
        haulier: null,
        account: null,
        booker: null,
        occupants: null,
      },
      risks: {
        targetingIndicators: {
          indicators: [],
          count: 0,
          score: 0,
        },
        matchedRules: [
          {
            id: 11470,
            name: 'PNR-Number in Party',
            type: 'Pre-arrival',
            priority: 'Tier 1',
            description: 'Test',
            version: 2,
            abuseTypes: [
              'Cash including AVTCs',
            ],
            indicatorMatches: [
              {
                entity: 'Booking',
                descriptor: 'numInParty',
                operator: 'greater_or_equal',
                value: '1',
              },
              {
                entity: 'Message',
                descriptor: 'mode',
                operator: 'in',
                value: '[Air Freight, Air Passenger, Fast Parcels, RORO Accompanied Freight, RORO Tourist, RORO Unaccompanied Freight]',
              },
            ],
          },
        ],
        matchedSelectorGroups: {
          groups: [],
          totalNumberOfSelectors: 0,
        },
        highestThreatLevel: {
          type: 'RULE',
          value: 'Tier 1',
        },
      },
    },
    {
      number: 2,
      createdAt: '2022-08-31T08:48:10.259770147Z',
      movement: {
        id: 'APIPNR:S=c85b5c5426a6696b24ac6ca7851f0987',
        status: 'PRE_ARRIVAL',
        mode: 'AIR_PASSENGER',
        description: 'individual',
        groupSize: 1,
        booking: {
          reference: 'PONQVFT',
          type: null,
          paymentMethod: null,
          bookedAt: null,
          checkInAt: '2019-07-20T16:43:35Z',
          tickets: [
            {
              number: '8888000991',
              type: 'ONE-WAY',
              price: null,
            },
            {
              number: '8888000993',
              type: 'ONE-WAY',
              price: null,
            },
          ],
          country: null,
          payments: [],
          agent: {
            iata: '890534932',
            location: 'LHR, GB',
          },
        },
        journey: {
          id: 'BA0103',
          direction: null,
          arrival: {
            country: null,
            location: 'PEK',
            time: '2019-07-21T18:35:00Z',
          },
          departure: {
            country: null,
            location: 'LHR',
            time: '2019-07-21T16:40:00Z',
          },
          route: [
            'LHR',
            'PEK',
          ],
          itinerary: [
            {
              id: 'BA0103',
              arrival: {
                country: null,
                location: 'PEK',
                time: '2019-07-21T18:35:00Z',
              },
              departure: {
                country: null,
                location: 'LHR',
                time: '2019-07-21T16:40:00Z',
              },
              duration: 6900000,
            },
          ],
          duration: 6900000,
        },
        vessel: null,
        person: {
          entitySearchUrl: null,
          name: {
            first: 'ZUES CARLO 17',
            last: 'BATZ STOUP 17',
            full: 'ZUES CARLO 17 BATZ STOUP 17',
          },
          role: 'PASSENGER',
          dateOfBirth: '1976-12-10T00:00:00Z',
          gender: 'M',
          nationality: 'GB',
          document: {
            entitySearchUrl: null,
            type: 'PASSPORT',
            number: '119039376',
            validFrom: '2018-04-27T00:00:00Z',
            expiry: '2023-04-26T00:00:00Z',
            countryOfIssue: 'GB',
          },
          movementStats: null,
          frequentFlyerNumber: '680419104BA',
          ssrCodes: [
            'FQTV',
            'RQST',
            'FQTR',
          ],
        },
        otherPersons: [
          {
            entitySearchUrl: null,
            name: {
              first: 'Joe',
              last: 'Peterson',
              full: 'Joe Peterson',
            },
            role: 'PASSENGER',
            dateOfBirth: '1981-06-03T00:00:00Z',
            gender: 'M',
            nationality: 'GB',
            document: {
              entitySearchUrl: null,
              type: 'PASSPORT',
              number: 'ST0394612',
              validFrom: null,
              expiry: '2021-02-01T00:00:00Z',
              countryOfIssue: 'GB',
            },
            movementStats: {
              movementCount: 3,
              examinationCount: 2,
              seizureCount: 1,
            },
            frequentFlyerNumber: '123456',
            ssrCodes: null,
          },
        ],
        flight: {
          departureStatus: 'DEPARTURE_CONFIRMED',
          number: 'BA0103',
          operator: 'BA',
          seatNumber: '34A',
        },
        baggage: {
          numberOfCheckedBags: null,
          weight: null,
          tags: [],
        },
        vehicle: null,
        trailer: null,
        goods: null,
        haulier: null,
        account: null,
        booker: null,
        occupants: null,
      },
      risks: {
        targetingIndicators: {
          indicators: [],
          count: 0,
          score: 0,
        },
        matchedRules: [
          {
            id: 11470,
            name: 'PNR-Number in Party',
            type: 'Pre-arrival',
            priority: 'Tier 1',
            description: 'Test',
            version: 2,
            abuseTypes: [
              'Cash including AVTCs',
            ],
            indicatorMatches: [
              {
                entity: 'Booking',
                descriptor: 'numInParty',
                operator: 'greater_or_equal',
                value: '1',
              },
              {
                entity: 'Message',
                descriptor: 'mode',
                operator: 'in',
                value: '[Air Freight, Air Passenger, Fast Parcels, RORO Accompanied Freight, RORO Tourist, RORO Unaccompanied Freight]',
              },
            ],
          },
        ],
        matchedSelectorGroups: {
          groups: [],
          totalNumberOfSelectors: 0,
        },
        highestThreatLevel: {
          type: 'RULE',
          value: 'Tier 1',
        },
      },
    },
    {
      number: 1,
      createdAt: '2022-08-31T08:47:48.082652711Z',
      movement: {
        id: 'APIPNR:S=c85b5c5426a6696b24ac6ca7851f0987',
        status: 'PRE_ARRIVAL',
        mode: 'AIR_PASSENGER',
        description: 'individual',
        groupSize: 1,
        booking: {
          reference: 'PONQVFT',
          type: null,
          paymentMethod: null,
          bookedAt: null,
          checkInAt: '2019-07-20T16:43:35Z',
          tickets: [
            {
              number: '8888000991',
              type: 'ONE-WAY',
              price: null,
            },
            {
              number: '8888000992',
              type: 'ONE-WAY',
              price: null,
            },
          ],
          country: null,
          payments: [],
          agent: {
            iata: '890534932',
            location: 'LHR, GB',
          },
        },
        journey: {
          id: 'BA0103',
          direction: null,
          arrival: {
            country: null,
            location: 'YYC',
            time: '2019-07-21T18:35:00Z',
          },
          departure: {
            country: null,
            location: 'LHR',
            time: '2019-07-21T16:40:00Z',
          },
          route: [
            'LHR',
            'YYC',
          ],
          itinerary: [
            {
              id: 'BA0103',
              arrival: {
                country: null,
                location: 'YYC',
                time: '2019-07-21T18:35:00Z',
              },
              departure: {
                country: null,
                location: 'LHR',
                time: '2019-07-21T16:40:00Z',
              },
              duration: 6900000,
            },
          ],
          duration: 6900000,
        },
        vessel: null,
        person: {
          entitySearchUrl: null,
          name: {
            first: 'ZUES CARLO 16',
            last: 'BATZ STOUP 16',
            full: 'ZUES CARLO 16 BATZ STOUP 16',
          },
          role: 'PASSENGER',
          dateOfBirth: '1976-12-10T00:00:00Z',
          gender: 'M',
          nationality: 'GB',
          document: {
            entitySearchUrl: null,
            type: 'PASSPORT',
            number: '119039375',
            validFrom: '2018-04-27T00:00:00Z',
            expiry: '2023-04-26T00:00:00Z',
            countryOfIssue: 'GB',
          },
          movementStats: null,
          frequentFlyerNumber: '680419104BA',
          ssrCodes: [
            'FQTV',
            'RQST',
            'FQTR',
          ],
        },
        otherPersons: [],
        flight: {
          departureStatus: 'DEPARTURE_CONFIRMED',
          number: 'BA0103',
          operator: 'BA',
          seatNumber: '34A',
        },
        baggage: {
          numberOfCheckedBags: null,
          weight: null,
          tags: [],
        },
        vehicle: null,
        trailer: null,
        goods: null,
        haulier: null,
        account: null,
        booker: null,
        occupants: null,
      },
      risks: {
        targetingIndicators: {
          indicators: [],
          count: 0,
          score: 0,
        },
        matchedRules: [
          {
            id: 11470,
            name: 'PNR-Number in Party',
            type: 'Pre-arrival',
            priority: 'Tier 1',
            description: 'Test',
            version: 2,
            abuseTypes: [
              'Cash including AVTCs',
            ],
            indicatorMatches: [
              {
                entity: 'Booking',
                descriptor: 'numInParty',
                operator: 'greater_or_equal',
                value: '1',
              },
              {
                entity: 'Message',
                descriptor: 'mode',
                operator: 'in',
                value: '[Air Freight, Air Passenger, Fast Parcels, RORO Accompanied Freight, RORO Tourist, RORO Unaccompanied Freight]',
              },
            ],
          },
        ],
        matchedSelectorGroups: {
          groups: [],
          totalNumberOfSelectors: 0,
        },
        highestThreatLevel: {
          type: 'RULE',
          value: 'Tier 1',
        },
      },
    },
  ],
};

export default mockData;
